---
name: test

releases:
- name: healthchecker
  version: create
  url: file://.
- name: bpm
  version: latest

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: healthchecker
  azs: [z1]
  instances: 1
  jobs:
  - name: example
    release: healthchecker
    properties: {}
  - name: bpm
    release: bpm
  vm_type: default
  stemcell: default
  networks:
  - name: default

